version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db_candlesticks'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./init.sql:/data/application/init.sql
    healthcheck:
      test: "/usr/bin/mysql --user=nayara --password=123456 --execute \"SHOW DATABASES;\""
      timeout: 10s
      interval: 10s
      retries: 5
    networks: 
      - default
  
  node:
    build: .
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      - db
